### PR TITLE
Feature/bare bones back end

### PR DESCRIPTION
**Pull request by ShawnBatson**
## Description ##
Created the bare bones for the table schema.
## Type ##
- [ ] This is a bugfix.
- [x] This is a new feature.
- [ ] This is part of a feature.
## Organization ##
- [x] Have you linked this pull request to a Trello card?
- [x] Have you named the branch in the format of feature/describe_feature_or_change OR bug/describe_bug_this_is_fixing 
## Review ##
- [ ] Is this a work in progress?
- [x] Is this ready to be reviewed?
- [x] Have you added two reviewers to this pull request?

### CODE REVIEW

**Review by abrobins — DISMISSED** [review]
nice work creating the db based on the spec. This will be a great starting point for development.

**Comment by abrobins** [comment]
@ShawnBatson you may want to change the description field in the template to describe what's going on with the code in this pull request.

**Comment by ShawnBatson** [comment]
[Create bare bones schema of tables to be fleshed out as individuals work on their components.](https://trello.com/c/ewGdW2VU/44-create-bare-bones-schema-of-tables-to-be-fleshed-out-as-individuals-work-on-their-components)

**Review by jessicagertig — DISMISSED** [review]
Good work Shawn.  The formatting was what I was going to mention but you fixed that before I had time to comment!

**Review by jessicagertig — APPROVED** [review]
Good job getting the seeds added in with the table structure.

**Review by Broast42 — COMMENTED** [review]
I like how you seeded in the dog breeds already. This will definitely help us when we get to that feature. I think you got all the breeds I could think of. Great job!

**Review by Broast42 — APPROVED** [review]
All looks good. I'll approve and push to main

**Pull request merged**
