### PR TITLE
Documentation/create router docs

### PR DESCRIPTION
**Pull request by JessBonanno**
## Description ##

Tested all endpoints and created documentation with postman to be found here:
https://documenter.getpostman.com/view/10971957/TVzViwN
- made small edits to migrations and seeds to clean code up where needed
- documented all endpoints with titles for readability

## Type ##

- [ ] This is a bugfix.
- [ ] This is a new feature.
- [ ] This is part of a feature.
- [x] This is documentation.

## Organization ##

- [ ] Have you linked this pull request to a Trello card?
- [x] Have you named the branch in the format of feature/describe_feature_or_change OR bug/describe_bug_this_is_fixing 

## Review ##

- [ ] Is this a work in progress?
- [x] Is this ready to be reviewed?
- [x] Have you added two reviewers to this pull request?

### CODE REVIEW

**Comment by JessBonanno** [comment]
[Create backend docs](https://trello.com/c/OGVtlgSK/44-create-backend-docs)

**Comment by riddlej9879** [comment]
The link give a 500 error. Is it just me?

**Review by riddlej9879 — APPROVED** [review]
Thanks for updating this information.

**Review by timotheemcdonald — APPROVED** [review]
Looks good to me

**Pull request merged**
